## Importing the library

In [ ]:
import numpy as np

### Creating a python list

In [ ]:
python_list = [1 , 2 , 3]
print(python_list)

[1, 2, 3]


In [ ]:
python_list.append(4)
print(python_list)

[1, 2, 3, 4]


### Creating a numpy array

In [ ]:
python_list = [1 , 2 , 3]
numpy_array = np.array(python_list)
print(numpy_array)

[1 2 3]


In [ ]:
numpy_array = np.array([1 , 2 , 3])
print(numpy_array)

[1 2 3]


### Numpy array operations 1

In [ ]:
# Append number
numpy_array = np.append(numpy_array , 4)
print(numpy_array)

[1 2 3 4]


In [ ]:
# Insert at index
print(numpy_array)
numpy_array = np.insert(numpy_array , 2 ,10)
print(numpy_array)

[1 2 3 4]
[ 1  2 10  3  4]


In [ ]:
# Delete Number (delete first encounter)
numpy_array = np.delete(numpy_array , 2 )
print(numpy_array)

[1 2 3 4]


In [ ]:
# Get Maximum/Minimum Number
print(numpy_array) 
max = np.max(numpy_array)
print(max)
min = np.min(numpy_array)
print(min)

[1 2 3 4]
4
1


In [ ]:
# Get Mean
print(numpy_array) 
mean = np.mean(numpy_array)
print(mean)

[1 2 3 4]
2.5


In [ ]:
# Get Unique values
numpy_array = np.array([1 , 1 , 1 , 2 , 3 ])
unique_values = np.unique(numpy_array)
print(unique_values) 

[1 2 3]


In [ ]:
# Get count of unique values
unique_values = np.unique(numpy_array , return_counts = True)
print(unique_values)

(array([1, 2, 3]), array([3, 1, 1]))


### Python List of List

In [ ]:
python_list_1 = [1 , 2 , 3] # shape is (3,nothing)
python_list_2 = [ [1 , 2 , 3]  , [1 , 2 , 3] ]  # shape is (2,3) A matrix
python_list_3 = [ [1 , 2 , 3]  ]  # shape is (1,3) A matrix

### Numpy Array 0 , 1 , and 2 Dimension

In [ ]:
numpy_arr_1 = np.array(python_list_1)
# print shape
print(numpy_arr_1.shape)
# print dimension
print(numpy_arr_1.ndim)

(3,)
1


In [ ]:
numpy_arr_2 = np.array(python_list_2)
# print shape
print(numpy_arr_2.shape)
# print dimension
print(numpy_arr_2.ndim)

(2, 3)
2


In [ ]:
numpy_arr_3 = np.array(python_list_3)
# print shape
print(numpy_arr_3.shape)
# print dimension
print(numpy_arr_3.ndim)

(1, 3)
2


### Numpy Array Operations 2

In [ ]:
# Array reshaping
python_list = [ [1 , 2 , 3]  , [1 , 2 , 3] ]  # shape is (2,3) A matrix
numpy_arr = np.array(python_list)
print(numpy_arr)
print("")
print(numpy_arr.shape)

[[1 2 3]
 [1 2 3]]

(2, 3)


In [ ]:
# Reshape (2,3) -> (1,6)
numpy_arr_resh = np.reshape(numpy_arr , (1,6))
print(numpy_arr_resh)
print("")
print(numpy_arr_resh.shape)

[[1 2 3 1 2 3]]

(1, 6)


In [ ]:
# Reshape (2,3) -> (1,6)
numpy_arr_resh = np.reshape(numpy_arr , (1,5))
print(numpy_arr_resh)
print("")
print(numpy_arr_resh.shape)

In [ ]:
# Array Transposing 
python_list = [ [1 , 1 , 1]  , [2 , 2 , 2] ]  # shape is (2,3) A matrix
numpy_arr = np.array(python_list)
print(numpy_arr)
print("")
print(numpy_arr.shape)

[[1 1 1]
 [2 2 2]]

(2, 3)


In [ ]:
import numpy as np
arra  = np.random.randint(100 , size = (3,4))
arra = np.reshape(arra,(2,6))
new = np.zeros((2,6))
arra = np.append(arra , new, axis = 0)
arra.shape

(4, 6)

In [ ]:
numpy_arr_tra = np.transpose(numpy_arr)
print(numpy_arr_tra)
print("")
print(numpy_arr_tra.shape)

[[1 2]
 [1 2]
 [1 2]]

(3, 2)


### Numpy Array Generation

In [ ]:
# Genereate array of zeros
zeros = np.zeros((3,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Genereate array of ones
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Genereate array of random integers
randoms=np.random.randint(100, size=(2 , 5))
print(randoms)

[[74 16 17 23 12]
 [88 98 51 80 66]]


In [ ]:
# Genereate array of random between 0 - 1
randoms=np.random.rand(2 , 5)
print(randoms)

[[0.32294517 0.40017102 0.06735066 0.43154777 0.09338675]
 [0.22842331 0.869912   0.81099576 0.05274806 0.99224848]]


### Numpy Array 3 Dimensions

In [ ]:
matrix_1 = np.array([
    [1 , 2 , 3] ,
    [4 , 5 , 6] ,
    [7 , 8 , 9]
])
print(matrix_1.ndim)
print(matrix_1.shape)

2
(3, 3)


In [ ]:
matrix_2 = np.array([
    [2 , 4 , 6] ,
    [8 , 10 , 12] ,
    [14 , 16 , 18]
])
print(matrix_2.ndim)
print(matrix_2.shape)


2
(3, 3)


In [ ]:
numpy_array = np.array([matrix_1 , matrix_2])
print(numpy_array)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]]


In [ ]:
print(numpy_array.shape)
print(numpy_array.ndim)

(2, 3, 3)
3


### Saving and loading

In [ ]:
# Saving
np.save("array.npy",numpy_array)

In [ ]:
# Load
array = np.load("array.npy")
print(array.shape)
print(array.ndim)

(2, 3, 3)
3
