# Create a 1-dimensional NumPy array of length 7 with random integers between 0 and 20. Insert the value 100 at the third index of the array. Then, delete the value at the fifth index of the array. Finally, calculate and print the minimum value and the unique values of the updated array

In [51]:
import numpy as np

In [52]:
a = np.random.randint(0,20,size = 7)
print(a)


[16 17  8  4 10 16 10]


In [53]:
a = np.insert(a,2,100)
print(a)

[ 16  17 100   8   4  10  16  10]


In [54]:
a = np.delete(a,4)
print(a)

[ 16  17 100   8  10  16  10]


In [55]:
print(a.min())

8


In [56]:
print(np.unique(a))

[  8  10  16  17 100]


# Create a 2D numpy array with dimensions (3,4) and fill it with random integers between 1 and 10. Then, append a row of zeros at the end of the array, and reshape the array to (4,4). Finally, find the maximum value in the array.


In [57]:
b = np.random.randint(1,10,(3,4))
print(b)

[[7 2 9 9]
 [6 8 6 2]
 [4 8 5 5]]


In [58]:
b = np.append(b,np.zeros(4))
print(b)

[7. 2. 9. 9. 6. 8. 6. 2. 4. 8. 5. 5. 0. 0. 0. 0.]


In [59]:
b = b.reshape(4,4)
print(b)

[[7. 2. 9. 9.]
 [6. 8. 6. 2.]
 [4. 8. 5. 5.]
 [0. 0. 0. 0.]]


# Create a 2D numpy array with dimensions (4,5) and fill it with random integers between 1 and 100. Then, insert a column of ones at index 2, and delete the first row of the array. Finally, compute the mean of the remaining elements in the array

In [60]:
c = np.random.randint(1,100,(4,5))
print(c)

[[33 55  7 32 76]
 [19 12 92 52 25]
 [91 53 12 60 82]
 [37 21 56 64 72]]


In [61]:
c = np.insert(c,2,np.ones(1),axis = 1)
print(c)

[[33 55  1  7 32 76]
 [19 12  1 92 52 25]
 [91 53  1 12 60 82]
 [37 21  1 56 64 72]]


In [62]:
c = np.delete(c,0,axis=1)
print(c)

[[55  1  7 32 76]
 [12  1 92 52 25]
 [53  1 12 60 82]
 [21  1 56 64 72]]


In [63]:
print(c.mean())

38.75


# Create a 3D numpy array of shape (2, 3, 4) filled with ones. Then, use the delete function to delete the second row of the second dimension. Print the resulting array

In [69]:
d = np.ones((2,3,4))
print(d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [70]:
d = np.delete(d,1,axis=2)
print(d,d.shape)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]] (2, 3, 3)


# Create a 3-dimensional numpy array with shape (2, 3, 4) and fill it with random numbers between 0 and 1. Then, reshape it into a 2-dimensional array with shape (6, 4).


In [66]:
e = np.random.randint(0,2,(2,3,4))
print(e)

[[[0 0 1 1]
  [0 1 1 1]
  [1 0 0 1]]

 [[1 0 1 1]
  [1 0 0 0]
  [0 1 1 0]]]


In [67]:
e = e.reshape((6,4))
print(e)

[[0 0 1 1]
 [0 1 1 1]
 [1 0 0 1]
 [1 0 1 1]
 [1 0 0 0]
 [0 1 1 0]]
