In [24]:
import numpy as np

In [28]:
a = np.random.randint(1,100,size=(4,5))
print(a)

[[48 19 46 65 82]
 [79 44 81 78 50]
 [23  8 81 40 41]
 [65 31 79 67 23]]


In [49]:
z = np.zeros(4)
print(z)
np.insert(a, 2, z,axis=1)

[0. 0. 0. 0.]


array([[48, 19,  0, 46, 65, 82],
       [79, 44,  0, 81, 78, 50],
       [23,  8,  0, 81, 40, 41],
       [65, 31,  0, 79, 67, 23]])

In [46]:
np.insert(a,2,np.zeros(1),axis=1)

array([[48, 19,  0, 46, 65, 82],
       [79, 44,  0, 81, 78, 50],
       [23,  8,  0, 81, 40, 41],
       [65, 31,  0, 79, 67, 23]])