In [2]:
import numpy as np

In [4]:
py_list = [1,2,3]
num_arr = np.array([1,2,3])

In [17]:
print(py_list)
print(num_arr)

[1, 2, 3]
[1 2 3 4]


In [18]:
num_arr = np.insert(num_arr,1,10)

In [19]:
print(num_arr)

[ 1 10  2  3  4]


In [20]:
num_arr = np.delete(num_arr,1)
print(num_arr)

[1 2 3 4]


In [22]:
max = np.max(num_arr)
print(max)
min = np.min(num_arr)
print(min)

4
1


In [24]:
mean = np.mean(num_arr)
print(mean)
print(max,min,mean)

2.5
4 1 2.5


In [25]:
arr = np.array([1,1,1,2,2,3,3,4])

In [26]:
print(np.unique(arr))

[1 2 3 4]


In [27]:
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4]), array([3, 2, 2, 1], dtype=int64))


In [29]:
arar = np.array([])
print(arar)

[]


In [32]:
arar = np.random.randint(100,size = 10)    
print(arar)

[15 27 92 77 63 27 58 82 13 48]


In [33]:
print(np.max(arar),np.mean(arar))

92 50.2


In [34]:
arar = np.append(arar,999)

In [35]:
print(np.max(arar),np.mean(arar))

999 136.45454545454547


In [49]:
arar = np.random.randint(50,size= 8)
print(arar)

[27 41 48 37 32 37 38 13]


In [50]:
arar = np.delete(arar,[2,4])
print(arar)

[27 41 37 37 38 13]


In [51]:
arar = np.insert(arar,[0,0],[100,200])
print(arar)

[100 200  27  41  37  37  38  13]


In [53]:
print(np.max(arar),"\n",np.min(arar),"\n",np.mean(arar))

200 
 13 
 61.625


In [54]:
py_list = [1,2,3]
py_list.append([4,5,6])
print(py_list)

[1, 2, 3, [4, 5, 6]]


In [55]:
py_list = [[1,2,3]]
py_list.append([4,5,6])

In [56]:
print(py_list)

[[1, 2, 3], [4, 5, 6]]


In [61]:
num_arr = np.array(py_list)

In [62]:
print(num_arr.shape)

(2, 3)


In [71]:
ar = [[1,2,3,4,5,6]]
new_arr = np.reshape(ar,(2,3))

In [72]:
tr_arr = np.transpose(new_arr)

In [73]:
print(new_arr)
print(tr_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [89]:
ff = np.random.randint(6,size=(3,4))
print(ff)

[[2 0 3 2]
 [4 2 0 2]
 [5 5 3 2]]


In [90]:
ff = np.reshape(ff,(2,6))
print(ff)

[[2 0 3 2 4 2]
 [0 2 5 5 3 2]]


In [94]:
ff = np.append(ff,12)
print(ff)

[ 2  0  3  2  4  2  0  2  5  5  3  2 12]


In [95]:
n_a = np.random.randint(12,size = (3,2))
x_a = np.random.randint(12,size = (3,2))
A = np.array([n_a,x_a])
print(A)

[[[10  7]
  [11  8]
  [11  6]]

 [[ 9  9]
  [ 4  1]
  [ 6  4]]]


In [96]:
A[0].shape

(3, 2)

In [97]:
A[1].shape

(3, 2)

In [98]:
A.shape

(2, 3, 2)